stages:
  - build
  - deploy

variables:
  PROJECT_NAME: hyperf
  REGISTRY_URL: registry-docker.org

# Job para construir e testar a imagem (executado em branches como 'test')
build_test_docker:
  stage: build
  # Correção: Definido como array vazio para evitar o erro "Incorrect type"
  before_script: [] 
  
  script:
    - docker build . -t $PROJECT_NAME
    - docker tag $PROJECT_NAME $REGISTRY_URL/$PROJECT_NAME:test
    - docker push $REGISTRY_URL/$PROJECT_NAME:test
  only:
    - test
  tags:
    - builder

# Job para deployar a imagem de teste (executado em branches como 'test')
deploy_test_docker:
  stage: deploy
  script:
    - docker stack deploy -c deploy.test.yml --with-registry-auth $PROJECT_NAME
  only:
    - test
  tags:
    - test

# Job para construir a imagem final (executado em tags)
build_docker:
  stage: build
  # Correção: Definido como array vazio para evitar o erro "Incorrect type"
  before_script: [] 
  
  script:
    - docker build . -t $PROJECT_NAME
    - docker tag $PROJECT_NAME $REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_NAME
    - docker tag $PROJECT_NAME $REGISTRY_URL/$PROJECT_NAME:latest
    - docker push $REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_NAME
    - docker push $REGISTRY_URL/$PROJECT_NAME:latest
  only:
    - tags
  tags:
    - builder

# Job para deployar a imagem final (executado em tags)
deploy_docker:
  stage: deploy
  script:
    - echo "Deploy para Produção/Staging iniciado."
    # Comando de deploy real (exemplo)
    # - docker stack deploy -c deploy.prod.yml --with-registry-auth $PROJECT_NAME
  only:
    - tags
  tags:
    - builder